// <auto-generated />
using System;
using Masar.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Masar.Infrastructure.Migrations
{
    [DbContext(typeof(MasarDbContext))]
    [Migration("20260826164835_IntegrateIdentityAndUserEnum")]
    partial class IntegrateIdentityAndUserEnum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Masar.Domain.Bookings.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid>("AlightingStationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AlightingStationID");

                    b.Property<Guid>("BoardingStationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BoardingStationID");

                    b.Property<string>("BookingReference")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getutcdate())", "DF__Bookings__CreatedAt__45F365D3");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF__Bookings__IsDelete__45F365D3");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PassengerID");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TripID");

                    b.HasKey("Id")
                        .HasName("PK__Bookings__73951ACD8A79C1D9");

                    b.HasIndex("AlightingStationId");

                    b.HasIndex("BoardingStationId");

                    b.HasIndex("PassengerId");

                    b.HasIndex("TripId");

                    b.HasIndex(new[] { "BookingReference" }, "UQ__Bookings__F9B66F614220A891")
                        .IsUnique();

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Masar.Domain.Carriages.Carriage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<int>("CarriageNumber")
                        .HasColumnType("int");

                    b.Property<string>("ClassType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getutcdate())", "DF__Carriages__CreatedAt__45F365D3");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF__Carriages__IsDelete__45F365D3");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.Property<Guid>("TrainId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TrainID");

                    b.HasKey("Id")
                        .HasName("PK__Carriage__17FE2DB09A454F45");

                    b.HasIndex(new[] { "TrainId", "CarriageNumber" }, "UQ_Train_Carriage")
                        .IsUnique();

                    b.ToTable("Carriages");
                });

            modelBuilder.Entity("Masar.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ExpiresOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasFilter("[Token] IS NOT NULL");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Masar.Domain.Passengers.Passenger", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getutcdate())", "DF__Passengers__CreatedAt__45F365D3");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PersonID");

                    b.HasKey("Id")
                        .HasName("PK_Customer");

                    b.HasIndex("PersonId");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("Masar.Domain.Persons.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getutcdate())", "DF__Persons__CreatedAt__45F365D3");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "UK_Persons_Email")
                        .IsUnique();

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Masar.Domain.RouteSegments.RouteSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("CorridorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getutcdate())", "DF__RouteSegments__CreatedAt__45F365D3");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DistanceKm")
                        .HasColumnType("decimal(6, 2)")
                        .HasColumnName("DistanceKM");

                    b.Property<int>("EstPassengerTimeMin")
                        .HasColumnType("int");

                    b.Property<Guid>("FromStationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FromStationID");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF__RouteSegments__IsDelete__45F365D3");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ToStationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ToStationID");

                    b.Property<string>("TrackType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__RouteSeg__C680609B5A711C10");

                    b.HasIndex("FromStationId");

                    b.HasIndex("ToStationId");

                    b.ToTable("RouteSegments");
                });

            modelBuilder.Entity("Masar.Domain.SavedPassengers.SavedPassenger", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getutcdate())", "DF__SavedPassengers__CreatedAt__45F365D3");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("NationalID");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserID");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SavedPassengers");
                });

            modelBuilder.Entity("Masar.Domain.Seats.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid>("CarriageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CarriageID");

                    b.Property<string>("ColumnPosition")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getutcdate())", "DF__Seats__CreatedAt__45F365D3");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF__Seats__IsDelete__45F365D3");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("SeatType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Standard");

                    b.HasKey("Id")
                        .HasName("PK__Seats__311713D35FB839DB");

                    b.HasIndex(new[] { "CarriageId", "SeatNumber" }, "UQ_Carriage_Seat")
                        .IsUnique();

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("Masar.Domain.Stations.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getutcdate())", "DF__Stations__CreatedAt__45F365D3");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomsDelayMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Governorate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF__Stations__IsDelete__45F365D3");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id")
                        .HasName("PK__Stations__E0D8A6DDFDE3D87F");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("Masar.Domain.SystemAuditLogs.SystemAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getutcdate())", "DF__SystemAuditLogs__CreatedAt__45F365D3");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EntityID");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Ipaddress")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("IPAddress");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserID");

                    b.HasKey("Id")
                        .HasName("PK__SystemAu__5E5499A89E782156");

                    b.ToTable("SystemAuditLogs");
                });

            modelBuilder.Entity("Masar.Domain.Tickets.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("BoardedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BookingID");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getutcdate())", "DF__Tickets__CreatedAt__45F365D3");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EndStopOrder")
                        .HasColumnType("int");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF__Tickets__IsDelete__45F365D3");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("QrcodeHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("QRCodeHash");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SeatID");

                    b.Property<int>("StartStopOrder")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Valid", "DF__Tickets__Status__76969D2E");

                    b.HasKey("Id")
                        .HasName("PK__Tickets__712CC627C667F94A");

                    b.HasIndex("BookingId");

                    b.HasIndex(new[] { "SeatId", "StartStopOrder", "EndStopOrder" }, "IX_Tickets_Seat_Stops");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Masar.Domain.TrainLiveLocations.TrainLiveLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getutcdate())", "DF__TrainLiveLocations__CreatedAt__45F365D3");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CurrentLatitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<decimal>("CurrentLongitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<Guid?>("CurrentSegmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CurrentSegmentID");

                    b.Property<decimal>("CurrentSpeedKmh")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("CurrentSpeedKMH");

                    b.Property<int>("DelayMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF__TrainLivedLocations__IsDelete__45F365D3");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedUtcdatetime2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("LastUpdatedUTCDatetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TripID");

                    b.HasKey("Id")
                        .HasName("PK__TrainLiv__A58A3418F1E17E41");

                    b.HasIndex("CurrentSegmentId");

                    b.HasIndex(new[] { "TripId", "LastUpdatedUtcdatetime2" }, "IX_LiveLocations_Trip");

                    b.ToTable("TrainLiveLocations");
                });

            modelBuilder.Entity("Masar.Domain.Trains.Train", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getutcdate())", "DF__Trains__CreatedAt__45F365D3");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CurrentStationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF__Trains__IsDelete__45E365D3");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxSpeedKmh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaxSpeedKMH")
                        .HasDefaultValue(120, "DF__Trains__MaxSpeed__440B1D61");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("Status")
                        .HasComment("0 -> Active, 1 -> Inactive, 2 -> Maintenance, 3 -> Cancelled.")
                        .HasDefaultValue((byte)0, "DF__Trains__Status__44FF419A");

                    b.Property<string>("TrainType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Trains__8ED2725A7F2931CC");

                    b.HasIndex("CurrentStationId");

                    b.HasIndex(new[] { "Code" }, "UQ__Trains__A25C5AA765BD0DBB")
                        .IsUnique();

                    b.ToTable("Trains", t =>
                        {
                            t.HasCheckConstraint("CK_Trains_Status", "[Status] IN (0, 1, 2, 3)");
                        });
                });

            modelBuilder.Entity("Masar.Domain.TripStops.TripStop", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getutcdate())", "DF__TripStops__CreatedAt__45F365D3");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DwellTimeMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsCustomsCheck")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF__TripStops__IsDelete__45F365D3");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScheduledArrival")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ScheduledDeparture")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StationID");

                    b.Property<int>("StopOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TripID");

                    b.HasKey("Id")
                        .HasName("PK__TripStop__4476150D060ADD54");

                    b.HasIndex("StationId");

                    b.HasIndex(new[] { "TripId", "StopOrder" }, "UQ_Trip_StopOrder")
                        .IsUnique();

                    b.ToTable("TripStops");
                });

            modelBuilder.Entity("Masar.Domain.Trips.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("ActualArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getutcdate())", "DF__Trips__CreatedAt__45F365D3");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DestinationStationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DestinationStationID");

                    b.Property<DateTime>("EstimatedArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF__Trips__IsDelete__45F365D3");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OriginStationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("OriginStationID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Scheduled");

                    b.Property<Guid>("TrainId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TrainID");

                    b.HasKey("Id")
                        .HasName("PK__Trips__51DC711E59245661");

                    b.HasIndex("DestinationStationId");

                    b.HasIndex("OriginStationId");

                    b.HasIndex(new[] { "TrainId", "DepartureTime", "EstimatedArrivalTime", "Status" }, "IX_Trips_SafetyCheck");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("Masar.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getutcdate())", "DF__Users__CreatedAt__693CA210");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF__Users__IsDelete__45F365D3");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PersonID");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Users__1788CCAC2F1F502E");

                    b.HasIndex("PersonId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Masar.Infrastructure.Identity.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Masar.Domain.Bookings.Booking", b =>
                {
                    b.HasOne("Masar.Domain.Stations.Station", "AlightingStation")
                        .WithMany("BookingAlightingStations")
                        .HasForeignKey("AlightingStationId")
                        .IsRequired()
                        .HasConstraintName("FK__Bookings__Alight__6FE99F9F");

                    b.HasOne("Masar.Domain.Stations.Station", "BoardingStation")
                        .WithMany("BookingBoardingStations")
                        .HasForeignKey("BoardingStationId")
                        .IsRequired()
                        .HasConstraintName("FK__Bookings__Boardi__6EF57B66");

                    b.HasOne("Masar.Domain.Passengers.Passenger", "Passenger")
                        .WithMany("Bookings")
                        .HasForeignKey("PassengerId")
                        .IsRequired()
                        .HasConstraintName("FK__Bookings__PassengerID__6D0D32F4");

                    b.HasOne("Masar.Domain.Trips.Trip", "Trip")
                        .WithMany("Bookings")
                        .HasForeignKey("TripId")
                        .IsRequired()
                        .HasConstraintName("FK__Bookings__TripID__6E01572D");

                    b.Navigation("AlightingStation");

                    b.Navigation("BoardingStation");

                    b.Navigation("Passenger");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Masar.Domain.Carriages.Carriage", b =>
                {
                    b.HasOne("Masar.Domain.Trains.Train", "Train")
                        .WithMany("Carriages")
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Carriages__Train__49C3F6B7");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("Masar.Domain.Passengers.Passenger", b =>
                {
                    b.HasOne("Masar.Domain.Persons.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Masar.Domain.RouteSegments.RouteSegment", b =>
                {
                    b.HasOne("Masar.Domain.Stations.Station", "FromStation")
                        .WithMany("RouteSegmentFromStations")
                        .HasForeignKey("FromStationId")
                        .IsRequired()
                        .HasConstraintName("FK__RouteSegm__FromS__3C69FB99");

                    b.HasOne("Masar.Domain.Stations.Station", "ToStation")
                        .WithMany("RouteSegmentToStations")
                        .HasForeignKey("ToStationId")
                        .IsRequired()
                        .HasConstraintName("FK__RouteSegm__ToSta__3D5E1FD2");

                    b.Navigation("FromStation");

                    b.Navigation("ToStation");
                });

            modelBuilder.Entity("Masar.Domain.SavedPassengers.SavedPassenger", b =>
                {
                    b.HasOne("Masar.Domain.Users.User", "User")
                        .WithMany("SavedPassengers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Masar.Domain.Seats.Seat", b =>
                {
                    b.HasOne("Masar.Domain.Carriages.Carriage", "Carriage")
                        .WithMany("Seats")
                        .HasForeignKey("CarriageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Seats__CarriageI__4D94879B");

                    b.Navigation("Carriage");
                });

            modelBuilder.Entity("Masar.Domain.Tickets.Ticket", b =>
                {
                    b.HasOne("Masar.Domain.Bookings.Booking", "Booking")
                        .WithMany("Tickets")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Tickets__Booking__74AE54BC");

                    b.HasOne("Masar.Domain.Seats.Seat", "Seat")
                        .WithMany("Tickets")
                        .HasForeignKey("SeatId")
                        .IsRequired()
                        .HasConstraintName("FK__Tickets__SeatID__75A278F5");

                    b.Navigation("Booking");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("Masar.Domain.TrainLiveLocations.TrainLiveLocation", b =>
                {
                    b.HasOne("Masar.Domain.RouteSegments.RouteSegment", "CurrentSegment")
                        .WithMany("TrainLiveLocations")
                        .HasForeignKey("CurrentSegmentId")
                        .HasConstraintName("FK__TrainLive__Curre__60A75C0F");

                    b.HasOne("Masar.Domain.Trips.Trip", "Trip")
                        .WithMany("TrainLiveLocations")
                        .HasForeignKey("TripId")
                        .IsRequired()
                        .HasConstraintName("FK__TrainLive__TripI__5FB337D6");

                    b.Navigation("CurrentSegment");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Masar.Domain.Trains.Train", b =>
                {
                    b.HasOne("Masar.Domain.Stations.Station", "CurrentStation")
                        .WithMany("Trains")
                        .HasForeignKey("CurrentStationId")
                        .HasConstraintName("FK__Trains__Curre__5EB337D6");

                    b.Navigation("CurrentStation");
                });

            modelBuilder.Entity("Masar.Domain.TripStops.TripStop", b =>
                {
                    b.HasOne("Masar.Domain.Stations.Station", "Station")
                        .WithMany("TripStops")
                        .HasForeignKey("StationId")
                        .IsRequired()
                        .HasConstraintName("FK__TripStops__Stati__5BE2A6F2");

                    b.HasOne("Masar.Domain.Trips.Trip", "Trip")
                        .WithMany("TripStops")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__TripStops__TripI__5AEE82B9");

                    b.Navigation("Station");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Masar.Domain.Trips.Trip", b =>
                {
                    b.HasOne("Masar.Domain.Stations.Station", "DestinationStation")
                        .WithMany("TripDestinationStations")
                        .HasForeignKey("DestinationStationId")
                        .IsRequired()
                        .HasConstraintName("FK__Trips__Destinati__5441852A");

                    b.HasOne("Masar.Domain.Stations.Station", "OriginStation")
                        .WithMany("TripOriginStations")
                        .HasForeignKey("OriginStationId")
                        .IsRequired()
                        .HasConstraintName("FK__Trips__OriginSta__534D60F1");

                    b.HasOne("Masar.Domain.Trains.Train", "Train")
                        .WithMany("Trips")
                        .HasForeignKey("TrainId")
                        .IsRequired()
                        .HasConstraintName("FK__Trips__TrainID__52593CB8");

                    b.Navigation("DestinationStation");

                    b.Navigation("OriginStation");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("Masar.Domain.Users.User", b =>
                {
                    b.HasOne("Masar.Domain.Persons.Person", "Person")
                        .WithMany("Users")
                        .HasForeignKey("PersonId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Persons");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Masar.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Masar.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Masar.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Masar.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Masar.Domain.Bookings.Booking", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Masar.Domain.Carriages.Carriage", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("Masar.Domain.Passengers.Passenger", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Masar.Domain.Persons.Person", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Masar.Domain.RouteSegments.RouteSegment", b =>
                {
                    b.Navigation("TrainLiveLocations");
                });

            modelBuilder.Entity("Masar.Domain.Seats.Seat", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Masar.Domain.Stations.Station", b =>
                {
                    b.Navigation("BookingAlightingStations");

                    b.Navigation("BookingBoardingStations");

                    b.Navigation("RouteSegmentFromStations");

                    b.Navigation("RouteSegmentToStations");

                    b.Navigation("Trains");

                    b.Navigation("TripDestinationStations");

                    b.Navigation("TripOriginStations");

                    b.Navigation("TripStops");
                });

            modelBuilder.Entity("Masar.Domain.Trains.Train", b =>
                {
                    b.Navigation("Carriages");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("Masar.Domain.Trips.Trip", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("TrainLiveLocations");

                    b.Navigation("TripStops");
                });

            modelBuilder.Entity("Masar.Domain.Users.User", b =>
                {
                    b.Navigation("SavedPassengers");
                });
#pragma warning restore 612, 618
        }
    }
}
