// <auto-generated />
using System;
using Masar.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Masar.Infrastructure.Migrations
{
    [DbContext(typeof(MasarDbContext))]
    partial class MasarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Masar.Infrastructure.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<int>("AlightingStationId")
                        .HasColumnType("int")
                        .HasColumnName("AlightingStationID");

                    b.Property<int>("BoardingStationId")
                        .HasColumnType("int")
                        .HasColumnName("BoardingStationID");

                    b.Property<string>("BookingReference")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("PassengerId")
                        .HasColumnType("int")
                        .HasColumnName("PassengerID");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("TripId")
                        .HasColumnType("int")
                        .HasColumnName("TripID");

                    b.HasKey("BookingId")
                        .HasName("PK__Bookings__73951ACD8A79C1D9");

                    b.HasIndex("AlightingStationId");

                    b.HasIndex("BoardingStationId");

                    b.HasIndex("PassengerId");

                    b.HasIndex("TripId");

                    b.HasIndex(new[] { "BookingReference" }, "UQ__Bookings__F9B66F614220A891")
                        .IsUnique();

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Masar.Infrastructure.Carriage", b =>
                {
                    b.Property<int>("CarriageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CarriageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarriageId"));

                    b.Property<int>("CarriageNumber")
                        .HasColumnType("int");

                    b.Property<string>("ClassType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.Property<int>("TrainId")
                        .HasColumnType("int")
                        .HasColumnName("TrainID");

                    b.HasKey("CarriageId")
                        .HasName("PK__Carriage__17FE2DB09A454F45");

                    b.HasIndex(new[] { "TrainId", "CarriageNumber" }, "UQ_Train_Carriage")
                        .IsUnique();

                    b.ToTable("Carriages");
                });

            modelBuilder.Entity("Masar.Infrastructure.Passenger", b =>
                {
                    b.Property<int>("PassengerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PassengerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PassengerId"));

                    b.Property<int>("PersonId")
                        .HasColumnType("int")
                        .HasColumnName("PersonID");

                    b.HasKey("PassengerId")
                        .HasName("PK_Customer");

                    b.HasIndex("PersonId");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("Masar.Infrastructure.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PersonID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<byte[]>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varbinary(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("PersonId");

                    b.HasIndex(new[] { "Email" }, "UK_Persons_Email")
                        .IsUnique();

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Masar.Infrastructure.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Role1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Role");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Masar.Infrastructure.RouteSegment", b =>
                {
                    b.Property<int>("SegmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SegmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SegmentId"));

                    b.Property<string>("CorridorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("DistanceKm")
                        .HasColumnType("decimal(6, 2)")
                        .HasColumnName("DistanceKM");

                    b.Property<int>("EstPassengerTimeMin")
                        .HasColumnType("int");

                    b.Property<int>("FromStationId")
                        .HasColumnType("int")
                        .HasColumnName("FromStationID");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("ToStationId")
                        .HasColumnType("int")
                        .HasColumnName("ToStationID");

                    b.Property<string>("TrackType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("SegmentId")
                        .HasName("PK__RouteSeg__C680609B5A711C10");

                    b.HasIndex("FromStationId");

                    b.HasIndex("ToStationId");

                    b.ToTable("RouteSegments");
                });

            modelBuilder.Entity("Masar.Infrastructure.SavedPassenger", b =>
                {
                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("NationalID");

                    b.Property<int>("SavedPassengerId")
                        .HasColumnType("int")
                        .HasColumnName("SavedPassengerID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.ToTable("SavedPassengers");
                });

            modelBuilder.Entity("Masar.Infrastructure.Seat", b =>
                {
                    b.Property<int>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SeatID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeatId"));

                    b.Property<int>("CarriageId")
                        .HasColumnType("int")
                        .HasColumnName("CarriageID");

                    b.Property<string>("ColumnPosition")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("SeatType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Standard");

                    b.HasKey("SeatId")
                        .HasName("PK__Seats__311713D35FB839DB");

                    b.HasIndex(new[] { "CarriageId", "SeatNumber" }, "UQ_Carriage_Seat")
                        .IsUnique();

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("Masar.Infrastructure.Station", b =>
                {
                    b.Property<int>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StationId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("CustomsDelayMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Governorate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("HasPassingLoop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("StationId")
                        .HasName("PK__Stations__E0D8A6DDFDE3D87F");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("Masar.Infrastructure.SystemAuditLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("LogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EntityID");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Ipaddress")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("IPAddress");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("LogId")
                        .HasName("PK__SystemAu__5E5499A89E782156");

                    b.ToTable("SystemAuditLogs");
                });

            modelBuilder.Entity("Masar.Infrastructure.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TicketID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketId"));

                    b.Property<DateTime?>("BoardedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    b.Property<int>("EndStopOrder")
                        .HasColumnType("int");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("QrcodeHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("QRCodeHash");

                    b.Property<int>("SeatId")
                        .HasColumnType("int")
                        .HasColumnName("SeatID");

                    b.Property<int>("StartStopOrder")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Valid", "DF__Tickets__Status__76969D2E");

                    b.HasKey("TicketId")
                        .HasName("PK__Tickets__712CC627C667F94A");

                    b.HasIndex("BookingId");

                    b.HasIndex(new[] { "SeatId", "StartStopOrder", "EndStopOrder" }, "IX_Tickets_Seat_Stops");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Masar.Infrastructure.Train", b =>
                {
                    b.Property<int>("TrainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TrainID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())", "DF__Trains__CreatedA__45F365D3");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_Trains_IsActive");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("MaxSpeedKmh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaxSpeedKMH")
                        .HasDefaultValue(120, "DF__Trains__MaxSpeed__440B1D61");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Active", "DF__Trains__Status__44FF419A");

                    b.Property<string>("TrainType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("TrainId")
                        .HasName("PK__Trains__8ED2725A7F2931CC");

                    b.HasIndex(new[] { "Code" }, "UQ__Trains__A25C5AA765BD0DBB")
                        .IsUnique();

                    b.ToTable("Trains");
                });

            modelBuilder.Entity("Masar.Infrastructure.TrainLiveLocation", b =>
                {
                    b.Property<long>("LiveLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("LiveLocationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LiveLocationId"));

                    b.Property<decimal>("CurrentLatitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<decimal>("CurrentLongitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<int?>("CurrentSegmentId")
                        .HasColumnType("int")
                        .HasColumnName("CurrentSegmentID");

                    b.Property<decimal>("CurrentSpeedKmh")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("CurrentSpeedKMH");

                    b.Property<int>("DelayMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdatedUtcdatetime2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("LastUpdatedUTCDatetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("TripId")
                        .HasColumnType("int")
                        .HasColumnName("TripID");

                    b.HasKey("LiveLocationId")
                        .HasName("PK__TrainLiv__A58A3418F1E17E41");

                    b.HasIndex("CurrentSegmentId");

                    b.HasIndex(new[] { "TripId", "LastUpdatedUtcdatetime2" }, "IX_LiveLocations_Trip");

                    b.ToTable("TrainLiveLocations");
                });

            modelBuilder.Entity("Masar.Infrastructure.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TripID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripId"));

                    b.Property<DateTime?>("ActualArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinationStationId")
                        .HasColumnType("int")
                        .HasColumnName("DestinationStationID");

                    b.Property<DateTime>("EstimatedArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("OriginStationId")
                        .HasColumnType("int")
                        .HasColumnName("OriginStationID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Scheduled");

                    b.Property<int>("TrainId")
                        .HasColumnType("int")
                        .HasColumnName("TrainID");

                    b.HasKey("TripId")
                        .HasName("PK__Trips__51DC711E59245661");

                    b.HasIndex("DestinationStationId");

                    b.HasIndex("OriginStationId");

                    b.HasIndex(new[] { "TrainId", "DepartureTime", "EstimatedArrivalTime", "Status" }, "IX_Trips_SafetyCheck");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("Masar.Infrastructure.TripStop", b =>
                {
                    b.Property<int>("TripStopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TripStopID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripStopId"));

                    b.Property<int>("DwellTimeMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsCustomsCheck")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ScheduledArrival")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ScheduledDeparture")
                        .HasColumnType("datetime2");

                    b.Property<int>("StationId")
                        .HasColumnType("int")
                        .HasColumnName("StationID");

                    b.Property<int>("StopOrder")
                        .HasColumnType("int");

                    b.Property<int>("TripId")
                        .HasColumnType("int")
                        .HasColumnName("TripID");

                    b.HasKey("TripStopId")
                        .HasName("PK__TripStop__4476150D060ADD54");

                    b.HasIndex("StationId");

                    b.HasIndex(new[] { "TripId", "StopOrder" }, "UQ_Trip_StopOrder")
                        .IsUnique();

                    b.ToTable("TripStops");
                });

            modelBuilder.Entity("Masar.Infrastructure.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())", "DF__Users__CreatedAt__693CA210");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int")
                        .HasColumnName("PersonID");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCAC2F1F502E");

                    b.HasIndex("PersonId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Masar.Infrastructure.Booking", b =>
                {
                    b.HasOne("Masar.Infrastructure.Station", "AlightingStation")
                        .WithMany("BookingAlightingStations")
                        .HasForeignKey("AlightingStationId")
                        .IsRequired()
                        .HasConstraintName("FK__Bookings__Alight__6FE99F9F");

                    b.HasOne("Masar.Infrastructure.Station", "BoardingStation")
                        .WithMany("BookingBoardingStations")
                        .HasForeignKey("BoardingStationId")
                        .IsRequired()
                        .HasConstraintName("FK__Bookings__Boardi__6EF57B66");

                    b.HasOne("Masar.Infrastructure.Passenger", "Passenger")
                        .WithMany("Bookings")
                        .HasForeignKey("PassengerId")
                        .IsRequired()
                        .HasConstraintName("FK__Bookings__PassengerID__6D0D32F4");

                    b.HasOne("Masar.Infrastructure.Trip", "Trip")
                        .WithMany("Bookings")
                        .HasForeignKey("TripId")
                        .IsRequired()
                        .HasConstraintName("FK__Bookings__TripID__6E01572D");

                    b.Navigation("AlightingStation");

                    b.Navigation("BoardingStation");

                    b.Navigation("Passenger");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Masar.Infrastructure.Carriage", b =>
                {
                    b.HasOne("Masar.Infrastructure.Train", "Train")
                        .WithMany("Carriages")
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Carriages__Train__49C3F6B7");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("Masar.Infrastructure.Passenger", b =>
                {
                    b.HasOne("Masar.Infrastructure.Person", "Person")
                        .WithMany("Passengers")
                        .HasForeignKey("PersonId")
                        .IsRequired()
                        .HasConstraintName("FK_Passengers_Persons");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Masar.Infrastructure.RouteSegment", b =>
                {
                    b.HasOne("Masar.Infrastructure.Station", "FromStation")
                        .WithMany("RouteSegmentFromStations")
                        .HasForeignKey("FromStationId")
                        .IsRequired()
                        .HasConstraintName("FK__RouteSegm__FromS__3C69FB99");

                    b.HasOne("Masar.Infrastructure.Station", "ToStation")
                        .WithMany("RouteSegmentToStations")
                        .HasForeignKey("ToStationId")
                        .IsRequired()
                        .HasConstraintName("FK__RouteSegm__ToSta__3D5E1FD2");

                    b.Navigation("FromStation");

                    b.Navigation("ToStation");
                });

            modelBuilder.Entity("Masar.Infrastructure.Seat", b =>
                {
                    b.HasOne("Masar.Infrastructure.Carriage", "Carriage")
                        .WithMany("Seats")
                        .HasForeignKey("CarriageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Seats__CarriageI__4D94879B");

                    b.Navigation("Carriage");
                });

            modelBuilder.Entity("Masar.Infrastructure.Ticket", b =>
                {
                    b.HasOne("Masar.Infrastructure.Booking", "Booking")
                        .WithMany("Tickets")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Tickets__Booking__74AE54BC");

                    b.HasOne("Masar.Infrastructure.Seat", "Seat")
                        .WithMany("Tickets")
                        .HasForeignKey("SeatId")
                        .IsRequired()
                        .HasConstraintName("FK__Tickets__SeatID__75A278F5");

                    b.Navigation("Booking");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("Masar.Infrastructure.TrainLiveLocation", b =>
                {
                    b.HasOne("Masar.Infrastructure.RouteSegment", "CurrentSegment")
                        .WithMany("TrainLiveLocations")
                        .HasForeignKey("CurrentSegmentId")
                        .HasConstraintName("FK__TrainLive__Curre__60A75C0F");

                    b.HasOne("Masar.Infrastructure.Trip", "Trip")
                        .WithMany("TrainLiveLocations")
                        .HasForeignKey("TripId")
                        .IsRequired()
                        .HasConstraintName("FK__TrainLive__TripI__5FB337D6");

                    b.Navigation("CurrentSegment");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Masar.Infrastructure.Trip", b =>
                {
                    b.HasOne("Masar.Infrastructure.Station", "DestinationStation")
                        .WithMany("TripDestinationStations")
                        .HasForeignKey("DestinationStationId")
                        .IsRequired()
                        .HasConstraintName("FK__Trips__Destinati__5441852A");

                    b.HasOne("Masar.Infrastructure.Station", "OriginStation")
                        .WithMany("TripOriginStations")
                        .HasForeignKey("OriginStationId")
                        .IsRequired()
                        .HasConstraintName("FK__Trips__OriginSta__534D60F1");

                    b.HasOne("Masar.Infrastructure.Train", "Train")
                        .WithMany("Trips")
                        .HasForeignKey("TrainId")
                        .IsRequired()
                        .HasConstraintName("FK__Trips__TrainID__52593CB8");

                    b.Navigation("DestinationStation");

                    b.Navigation("OriginStation");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("Masar.Infrastructure.TripStop", b =>
                {
                    b.HasOne("Masar.Infrastructure.Station", "Station")
                        .WithMany("TripStops")
                        .HasForeignKey("StationId")
                        .IsRequired()
                        .HasConstraintName("FK__TripStops__Stati__5BE2A6F2");

                    b.HasOne("Masar.Infrastructure.Trip", "Trip")
                        .WithMany("TripStops")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__TripStops__TripI__5AEE82B9");

                    b.Navigation("Station");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Masar.Infrastructure.User", b =>
                {
                    b.HasOne("Masar.Infrastructure.Person", "Person")
                        .WithMany("Users")
                        .HasForeignKey("PersonId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Persons");

                    b.HasOne("Masar.Infrastructure.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Roles");

                    b.Navigation("Person");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Masar.Infrastructure.Booking", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Masar.Infrastructure.Carriage", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("Masar.Infrastructure.Passenger", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Masar.Infrastructure.Person", b =>
                {
                    b.Navigation("Passengers");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Masar.Infrastructure.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Masar.Infrastructure.RouteSegment", b =>
                {
                    b.Navigation("TrainLiveLocations");
                });

            modelBuilder.Entity("Masar.Infrastructure.Seat", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Masar.Infrastructure.Station", b =>
                {
                    b.Navigation("BookingAlightingStations");

                    b.Navigation("BookingBoardingStations");

                    b.Navigation("RouteSegmentFromStations");

                    b.Navigation("RouteSegmentToStations");

                    b.Navigation("TripDestinationStations");

                    b.Navigation("TripOriginStations");

                    b.Navigation("TripStops");
                });

            modelBuilder.Entity("Masar.Infrastructure.Train", b =>
                {
                    b.Navigation("Carriages");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("Masar.Infrastructure.Trip", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("TrainLiveLocations");

                    b.Navigation("TripStops");
                });
#pragma warning restore 612, 618
        }
    }
}
